Properly manage folder/file permissions
YunoHost/example_ynh pull request #147
Opened 2021-03-17 15:35 UTC by alexAubin

## Problem

Follow-up of last days discussions about securing folders and files

## Solution

- Create the app user asap, and in particular before `yhn_setup_source`
- Run the `chmod`/`chown` as soon as possible after setting up the files, to prevent an attacker from being able to access/edit files during the few seconds/minutes corresponding to other steps
- Explicit `chmod` to remove any permissions to "others"

## PR Status

Yolocommited

2021-03-17 19:56 UTC, yalh76 requested changes

2021-03-17 19:56 UTC, yalh76 commented on scripts/install
> +chmod 400
```suggestion
chmod 400 "$final_path/some_config_file"
```

2021-03-17 19:56 UTC, yalh76 commented on scripts/upgrade
> +chmod 400
```suggestion
chmod 400 "$final_path/some_config_file"
```

2021-03-18 00:51 UTC, yalh76 approved these changes

2021-03-21 07:41 UTC, ericgaspar approved these changes

2021-04-06 20:29 UTC, merged