Implement GitHub Action to automatically upgrade from upstream
YunoHost/example_ynh pull request #172
Opened 2021-09-04 20:47 UTC by tituspijean

## Problem

- App maintenance is tedious and can be repetitive

## Solution

- Use GitHub Actions with a cron job to check daily for new releases from the upstream app. If a new release is detected:
   - `updater.sh` is run to update the source files (script to be edited by the maintainers, hopefully once and for all)
   - a PR is then created. 🎉 

N.B.:
- Automatic CI testing depends on: https://github.com/YunoHost/yunorunner/pull/25
- We may not want to have these files included in the example app, at risk of having the actions run before the script is ready.
   - maybe we can add a `exit 1` at the top of the script, or whatever, to stop the action by default, and leave it to the maintainers to remove it when they are ready.
   - or disable actions by default in the repositories?

2021-09-07 21:09 UTC, yalh76 approved these changes

2021-09-16 07:07 UTC, ericgaspar requested changes

2021-09-16 07:07 UTC, ericgaspar commented on .github/workflows/updater.sh
> +jq -s --indent 4 ".[] | .version = \"$VERSION~ynh1\"" manifest.json | sponge manifest.json
```suggestion
jq -s --indent 4 ".[] | .version = \"$version~ynh1\"" manifest.json | sponge manifest.json
```

2021-09-16 07:08 UTC, ericgaspar commented on .github/workflows/updater.sh
> +jq -s --indent 4 ".[] | .version = \"$VERSION~ynh1\"" manifest.json | sponge manifest.json
Following the chat debug session :)

2021-09-16 10:43 UTC, ericgaspar commented on .github/workflows/updater.sh
> +
```
if [[ ${version:0:1} == "v" || ${version:0:1} == "V" ]]; then
    version=${version:1}
fi
```
Is it worth adding this little chunk?

2021-09-16 18:42 UTC, tituspijean commented on .github/workflows/updater.sh
> +
There may be plenty other ways for tag names not to fit quite well, but I guess this one may occur often. Let's add it yes. 😃

2021-11-16 09:03 UTC, ericgaspar approved these changes

2021-11-16 21:12 UTC, merged