Improve systemd hardening
YunoHost/example_ynh pull request #180
Opened 2022-01-19 18:43 UTC by alexAubin

## Changes

- A couple minor things for systemd hardening taken from https://news.ycombinator.com/item?id=29976096. Not a huge deal, i.e. it's not like we gotta absolutely apply this to every app already implementing some form of hardening, it's just nice to have.

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-01-26 07:47 UTC, tituspijean commented
Oooh, what about this one? Seems to be a perfect fit for most apps serving only on an internal port.

```
  SocketBindDeny=any
  SocketBindAllow=tcp:__PORT__
```

2022-01-28 22:18 UTC, tituspijean commented on conf/systemd.service
> +ProtectProc=invisible
⚠️ These unit file settings were not introduced within the same Systemd version and will not all work.
My current YunoHost v4.3.6 ships Systemd version 241, for example. A recently installed beta YunoHost 11.0.2 ships Systemd 247.3-6.

| unit file settings | Systemd version |
|------------------|-----------------| 
`ProtectClock` | 247
`ProtectHostname` | 242
`ProtectKernelLogs` | 250
`ProtectProc` | 247

2022-01-29 13:29 UTC, alexAubin commented on conf/systemd.service
> +ProtectProc=invisible
Ah, thanks for checking this :sweat_smile: 

So not merging before bullseye, and even then we shall only have `ProtectClock`, `Hostname` and `Proc` ?

2022-08-15 06:01 UTC, ericgaspar approved these changes

2022-08-15 18:40 UTC, Tagadda requested changes

2022-08-15 18:40 UTC, Tagadda commented on conf/systemd.service
> +ProtectProc=invisible
```suggestion
ProtectClock=yes
ProtectHostname=yes
ProtectProc=invisible
```

2022-11-20 16:53 UTC, merged