READMEs update
YunoHost/example_ynh pull request #191
Opened 2022-06-06 17:46 UTC by OniriCorpe

## Problem

- Example READMEs are not up to date

## Solution

- Update them according to:
https://github.com/YunoHost/apps/pull/1430
https://github.com/YunoHost/apps/pull/1445
https://github.com/YunoHost/apps/pull/1446

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

2022-06-06 21:21 UTC, tituspijean requested changes

2022-06-06 21:21 UTC, tituspijean commented on README.md
> +# Packaging your an app, starting from this example
You are weirdly restoring a typo fixed by https://github.com/YunoHost/example_ynh/commit/d4fa8d57d24386438ca35d486a08fcd66b9ed5e6: 😛 
```suggestion
# Packaging an app, starting from this example
```

2022-06-06 21:21 UTC, tituspijean commented on README_fr.md
>  # Example app pour YunoHost
```suggestion
# Exemple d'app pour YunoHost
```

2022-06-06 22:16 UTC, OniriCorpe commented on README.md
> +# Packaging your an app, starting from this example
The typo is in the [README-generator](https://github.com/YunoHost/apps/tree/master/tools/README-generator) template, so we should better correct it there :)

2022-06-06 22:18 UTC, OniriCorpe commented on README_fr.md
>  # Example app pour YunoHost
j'aurais tendance à etre d'accord, mais La correction sera défaite à chaque mise à jour des fichiers en concordance avec le générateur :/

2022-06-07 11:06 UTC, tituspijean commented on README_fr.md
>  # Example app pour YunoHost
Je ne pense pas que le robot soit actif sur ce dépôt, donc ça passerait je pense. C'est quand le *template* est utilisé et le nouveau dépôt créé dans YunoHost-Apps que le texte risque d'être changé. Je ne pense pas que ça doit trop gênant.

2022-06-07 20:49 UTC, yalh76 commented on README.md
> +# Packaging your an app, starting from this example
Corrected in [README-generator](https://github.com/YunoHost/apps/tree/master/tools/README-generator)

2022-06-07 20:49 UTC, yalh76 approved these changes

2022-06-08 02:05 UTC, OniriCorpe commented on README_fr.md
>  # Example app pour YunoHost
Dans ce cas pourquoi conserver du code spécifique à ce dépôt dans le template anglophone ? 😅😅

Ça rend confus d'avoir un comportement spécifique du générateur pour ce dépôt mais qu'il soit bidouillé ici au risque qu'il saute à chaque fois que quelqu'un voudra naïvement mettre les 2 en concordance comme moi

2022-06-08 05:06 UTC, tituspijean approved these changes

2022-06-08 05:06 UTC, merged